[package]
categories = ["api-bindings", "cryptography::cryptocurrencies"]
description = "A Rust client library for the Coinbase Advanced Trade API"
documentation = "https://docs.rs/coinbase-advanced"
edition = "2024"
keywords = ["coinbase", "cryptocurrency", "trading", "api", "websocket"]
license = "MIT"
name = "coinbase-advanced"
readme = "README.md"
repository = "https://github.com/dcompoze/coinbase-advanced"
rust-version = "1.85"
version = "2.0.2"

[features]
default = ["rustls-tls"]
native-tls = ["reqwest/native-tls", "tokio-tungstenite/native-tls"]
rustls-tls = ["reqwest/rustls", "tokio-tungstenite/rustls-tls-native-roots"]

[lib]
name = "coinbase_advanced"
path = "src/lib.rs"

[dependencies]
futures = "0.3.31"
hex = "0.4"
reqwest = { version = "0.13.1", default-features = false, features = ["charset", "http2", "json", "system-proxy"] }
reqwest-middleware = { version = "0.5.2", features = ["json"] }
reqwest-retry = "0.9.0"
reqwest-tracing = "0.7.1"
ring = "0.17"
secrecy = "0.10.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
serde_urlencoded = "0.7"
thiserror = "2.0.17"
tokio = { version = "1.49.0", features = ["rt", "macros"] }
tokio-tungstenite = { version = "0.30.0", default-features = false, features = ["connect"] }
tracing = "0.1.44"
url = "2.5.8"

[dev-dependencies]
dotenv = "0.15"
futures = "0.3"
tokio = { version = "1.49", features = ["full"] }
tokio-test = "0.4"
tokio-tungstenite = "0.30"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
wiremock = "0.6"
